"""
services/publisher.py
=====================
Auto-generated by agency-agents engineering pipeline.
Handles multi-platform video publishing (TikTok, YouTube, Douyin, Instagram).
"""
from abc import ABC, abstractmethod
import requests
import logging

logger = logging.getLogger(__name__)

class BasePublisher(ABC):
    """
    Abstract base class for platform-specific publishers.
    """

    @abstractmethod
    def publish(self, video_path: str, metadata: dict) -> dict:
        """
        Publish a video to the platform.

        :param video_path: Path to the video file.
        :param metadata: Metadata for the video (e.g., title, description).
        :return: Result of the publish action (e.g., success status, video URL).
        """
        pass

# Utility function for HTTP requests to handle errors and non-JSON responses
def safe_post(url, data):
    try:
        response = requests.post(url, data=data, timeout=30)
        response.raise_for_status()
        try:
            return response.json()
        except ValueError:
            return {"error": "Invalid JSON response"}
    except requests.RequestException as e:
        return {"error": str(e)}

class TikTokPublisher(BasePublisher):
    def publish(self, video_path: str, metadata: dict) -> dict:
        logger.info(f"Uploading {video_path} to TikTok...")
        response = safe_post("https://api.tiktok.com/upload", {"video_path": video_path, **metadata})
        return {"status": "success" if "error" not in response else "failed", "platform": "TikTok", "response": response}

class YouTubeShortsPublisher(BasePublisher):
    def publish(self, video_path: str, metadata: dict) -> dict:
        logger.info(f"Uploading {video_path} to YouTube Shorts...")
        response = safe_post("https://api.youtube.com/shorts/upload", {"video_path": video_path, **metadata})
        return {"status": "success" if "error" not in response else "failed", "platform": "YouTube Shorts", "response": response}

class DouyinPublisher(BasePublisher):
    def publish(self, video_path: str, metadata: dict) -> dict:
        logger.info(f"Uploading {video_path} to Douyin...")
        response = safe_post("https://api.douyin.com/upload", {"video_path": video_path, **metadata})
        return {"status": "success" if "error" not in response else "failed", "platform": "Douyin", "response": response}

class InstagramReelsPublisher(BasePublisher):
    def publish(self, video_path: str, metadata: dict) -> dict:
        logger.info(f"Uploading {video_path} to Instagram Reels...")
        response = safe_post("https://api.instagram.com/reels/upload", {"video_path": video_path, **metadata})
        return {"status": "success" if "error" not in response else "failed", "platform": "Instagram Reels", "response": response}
