"""
services/viral_copywriter.py
============================
Auto-generates viral and engaging titles, descriptions, and hashtags for social media
using the LLM API, based on the video's context and contents.
"""
import json
import logging
from openai import AsyncOpenAI

logger = logging.getLogger(__name__)

class ViralCopywriter:
    def __init__(self, config: dict):
        self.config = config
        
        # Determine API credentials (fallback to standard OpenAI if KIE is not present)
        api_key = config.get("kie", {}).get("api_key") or config.get("openai", {}).get("api_key")
        base_url = config.get("kie", {}).get("base_url") or config.get("openai", {}).get("base_url", "https://api.openai.com/v1")
        self.model = config.get("viral_copywriter", {}).get("model", "gpt-4o")
        
        if not api_key:
            logger.warning("ViralCopywriter: No API key provided in config. Generations will likely fail.")
            
        self.client = AsyncOpenAI(api_key=api_key, base_url=base_url)

    async def generate_content(self, video_context: str) -> dict:
        """
        Calls the LLM to generate a viral title, description, and hashtags.
        Returns a dict: {"title": "...", "description": "...", "tags": ["...", "..."]}
        """
        prompt = (
            f"You are a top-tier TikTok/Douyin viral copywriter and marketer.\n"
            f"Based on the following video context, generate an extremely catchy, viral title (under 50 chars), "
            f"an engaging description that drives comments, and a list of 5 highly trending hashtags.\n\n"
            f"VIDEO CONTEXT:\n{video_context}\n\n"
            f"You MUST return valid JSON ONLY with the exact keys: 'title', 'description', 'tags' (array of strings)."
        )

        try:
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are a JSON-only viral marketing AI."},
                    {"role": "user", "content": prompt}
                ],
                response_format={"type": "json_object"},
                temperature=0.8,
            )
            
            result_text = response.choices[0].message.content
            viral_data = json.loads(result_text)
            
            # Formatting safety
            return {
                "title": str(viral_data.get("title", ""))[:80],
                "description": str(viral_data.get("description", "")),
                "tags": viral_data.get("tags", [])
            }
        except Exception as e:
            logger.error(f"ViralCopywriter generation failed: {e}")
            # Safe Fallback
            return {
                "title": "AI Generated Viral Video",
                "description": "Check out this amazing video generated by AI! #AI #Video",
                "tags": ["AI", "Video", "Trending"]
            }
