import os
import asyncio
import httpx
from typing import Dict, Any, Optional
from utils.logger import get_logger

logger = get_logger(__name__)

class RunPodAPIClient:
    """
    Client for triggering requests to a custom RunPod Serverless API endpoint hosting SVI.
    """
    
    def __init__(self, api_key: str = None, endpoint_id: str = None):
        self.api_key = api_key or os.environ.get("RUNPOD_API_KEY")
        self.endpoint_id = endpoint_id or os.environ.get("RUNPOD_ENDPOINT_ID")
        self.base_url = f"https://api.runpod.ai/v2/{self.endpoint_id}"
        
        if not self.api_key or not self.endpoint_id:
            logger.warning("RUNPOD_API_KEY or RUNPOD_ENDPOINT_ID is missing. API calls will fail.")

    async def generate_video(self, prompt: str, image_url: Optional[str] = None, timeout: int = 300) -> str:
        """
        Submits job to RunPod Serverless and polls for completion.
        Returns the video URL generated by the worker.
        """
        logger.info(f"Submitting SVI task to RunPod Serverless with prompt: {prompt[:50]}...")
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }
        
        payload = {
            "input": {
                "prompt": prompt,
                "image_url": image_url
            }
        }
        
        try:
            async with httpx.AsyncClient(timeout=timeout) as client:
                # 1. Submit the job
                submit_res = await client.post(f"{self.base_url}/run", json=payload, headers=headers)
                submit_res.raise_for_status()
                
                job_id = submit_res.json().get("id")
                if not job_id:
                    raise ValueError("Failed to get job ID from RunPod")
                    
                logger.info(f"RunPod job started with ID: {job_id}. Polling for completion...")
                
                # 2. Poll for completion
                status_url = f"{self.base_url}/status/{job_id}"
                while True:
                    await asyncio.sleep(5)  # Poll every 5 seconds
                    status_res = await client.get(status_url, headers=headers)
                    status_res.raise_for_status()
                    
                    data = status_res.json()
                    status = data.get("status")
                    
                    if status == "COMPLETED":
                        output = data.get("output", {})
                        video_url = output.get("video_url")
                        if not video_url:
                            logger.error(f"RunPod job completed but no video_url found. Full output: {output}")
                            raise ValueError("Output payload missing video_url")
                        logger.info(f"RunPod generation successful: {video_url}")
                        return video_url
                        
                    elif status in ["FAILED", "CANCELLED"]:
                        logger.error(f"RunPod job failed! ID: {job_id}, Data: {data}")
                        raise RuntimeError(f"RunPod Serverless Error: {data.get('error')}")
                        
        except httpx.HTTPStatusError as e:
            logger.error(f"HTTP error during RunPod API call: {e.response.status_code} - {e.response.text}")
            raise
        except httpx.TimeoutException:
            logger.error("Timeout waiting for RunPod HTTP response.")
            raise
        except Exception as e:
            logger.error(f"Unexpected error communicating with RunPod: {str(e)}")
            raise
